import Image from "next/image";
import Sidebar from "@/components/Sidebar/Sidebar";

export default function Home() {
  return (
    <div className="bg-white">
      <head>
        <title>musique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main className="flex min-h-screen max-w-7xl mx-auto">
        <Sidebar />
      </main>
    </div>
  );
}
